<?php
/**
 * @file
 * Drupal needs this blank file.
 */

function bloom_node_access($node, $op, $account) {
  $type = is_string($node) ? $node : $node->type;
  
  if ( $type == 'hipaa_pii') {
      if (in_array('HIPAAmaster', $account->roles)) {
          return NODE_ACCESS_ALLOW;
      }
      else {
          return NODE_ACCESS_DENY;
      }
  }
  // Returning nothing from this function would have the same effect.
  return NODE_ACCESS_IGNORE;
}
